### PR TITLE
fixed unit tests.

### PR DESCRIPTION
**Pull request by un7c0rn**

### CODE REVIEW

**Comment by un7c0rn** [comment]
/cc @dzx11 
/cc @bernardbaker 

- bring up and tear down a new AWS queue for each game so that events don't leak across environments.
- fixed an issue with the core game loop merging algorithm.
- reconciled terminology and semantics around _counting_, e.g. no longer use "size" which is ambiguous. instead count_players, count_teams, count_tribes. it's critical that these counters maintain fidelity from initialization all the way through game completion.

**Comment by un7c0rn** [comment]
@bernardbaker we'll need to make sure counts are handled the same way in the FE.

**Comment by bernardbaker** [comment]
@un7c0rn could you create an issue for this change on the front end?

**Comment by un7c0rn** [comment]
> @un7c0rn could you create an issue for this change on the front end?

Sure!

**Pull request merged**
