### PR TITLE
first pass full game simulation using emulated players.

### PR DESCRIPTION
**Pull request by un7c0rn**

### CODE REVIEW

**Comment by un7c0rn** [comment]
untested but once this passes, all we need to do is:

- deploy this repo and start the match maker service on GCP
- deploy FE and ensure ATP passes

**Comment by un7c0rn** [comment]
Updated. Integration tests still not passing but much further along. @dzx11 @bernardbaker PTAL

Screen Shot 2020-09-15 at 2 51 40 AM 

Screen Shot 2020-09-15 at 2 49 53 AM

Screen Shot 2020-09-15 at 2 51 56 AM

**Comment by bernardbaker** [comment]
@un7c0rn that looks fantastic.

**Comment by un7c0rn** [comment]
> @un7c0rn that looks fantastic.

@bernardbaker Thanks Bernard!

**Review by dzx11 — COMMENTED** [review]
@un7c0rn LGTM. The only issue is that Sentry free tier has a limit of 50k errors per month and we might go over that. Maybe moving the integration test to a separate branch and having the master branch not log to Sentry could be a good idea. 

Also I noticed that there were some code formatting changes. Have we decided on a linting tool or style guide for the Python side?

**Comment by bernardbaker** [comment]
It really does! Great work.

Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
> @un7c0rn LGTM. The only issue is that Sentry free tier has a limit of 50k errors per month and we might go over that. Maybe moving the integration test to a separate branch and having the master branch not log to Sentry could be a good idea.
> 
> Also I noticed that there were some code formatting changes. Have we decided on a linting tool or style guide for the Python side?

@dzx11 Agreed I turned off Sentry (hit the limit pretty quick with integration testing). Yea I enabled auto PEP8 formatting in my IDE so that's where the format changes are coming from.

**Pull request merged**
