### PR TITLE
Setup event queue service and write good tests

### LINKED ISSUE #5: Setup event queue service and write good tests
The event queue service is critical for keeping players informed about what's going on in the game in realtime. We don't need to build an event queue, but we need to pick a good one and set it up. Once it's setup we can plug it into the core game engine by deriving from the EventQueue abstract class with a new implementation. The second important aspect is writing hooks that confirm the right events are being queued based on what's happening in game simulations.

### PR DESCRIPTION
**Pull request by un7c0rn**

### CODE REVIEW

**Comment by un7c0rn** [comment]
@bernardbaker @dzx11 PTAL. Note that the test instance credentials are included in the repository because our CI bot uses them to run all of the tests. These are not the prod instance credentials. Current plan is to revoke these keys as we get closer to launch, haven't thought of a good way to give PR bot access to test instance without storing in repo and without significantly reducing developer velocity. Interested in your thoughts.

**Comment by dzx11** [comment]
@un7c0rn why not store the credentials as environment variables, which can then be grabbed with os.environ[...]? We can write a shell script to set the environment variables, which will be kept off the repo, and uploaded to certain machines as necessary. The CI hopefully has a way to set environment variables manually as well.

**Comment by un7c0rn** [comment]
@dzx11 That makes sense to me at a high level but how do the credentials get set in the GitHub PR bot VM? It looks like variables are set using the workflow file, but that file is publicly visible. If we write a shell script that downloads the credentials from an off-repo location, the shell script is also visible.

https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables

**Comment by dzx11** [comment]
@un7c0rn it looks like github provides a way to encrypt secrets: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

I'm not sure how this would impact the local development environment, however.

**Comment by bernardbaker** [comment]
Hi guys,

I've always injected them from a secured build environment.

David could you look into the GitHub solution?

Regards,
Bernard

**Comment by un7c0rn** [comment]
@dzx11 Awesome find I think this is exactly what we need. Creating a tracking issue and merging so I can start the Twilio integration.

https://github.com/un7c0rn/stopthevirus/issues/53

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Pull request merged**
