### PR TITLE
Feature/unify repos

### PR DESCRIPTION
**Pull request by bernardbaker**
1) The folder structure is more organised.
2) The project documentation has been updated to find the images (banner.png, etc).
3) The 'virus-fe' folder has been replaced with 'react front end'.
4) The basic SPA has been updated.
5) Instructions on how to create a Netlify account are in the 'react front end' README.md.
6) A develop branch has been created.
7) All features branches created should be like 'feature/login', 'feature/unify-repos', not 'login' or 'unify-repos'.

### CODE REVIEW

**Review by un7c0rn — CHANGES_REQUESTED** [review]
@bernardbaker Thanks for the unification! A few minor notes:

1. The top level directory restructure looks good but breaks the python unit tests due to import resolution. I think we should leave python code as is until we're ready to refactor any associated tests. Should be a relatively straightforward fix but we've got other tasks to get to short term. Documentation folder changes look good to go.

2. For convention with certain terminals / editors please use underscores in directory names. For example "react front end" -> react_frontend

3. It looks like the base SPA from #11 changes in this PR. It would be ideal if the unification updates still resulted in the same SPA layout from #11 as our starting point, as I think David is planning to continue page implementation from there. @dzx11 Please advise.

Confirmed locally by:

Updating node to v12.16.1
cd stopthevirus/react\ front\ end
yarn
yarn start

**Comment by bernardbaker** [comment]
Hi everyone,

1) Don't you think it's messy to leave the python scripts there? Can't the
test import code be updated to reference the correct resources? There
shouldn't be any source code files in the base of the repo anymore, it's
good practice to remove them.

2) I'll get that updated tomorrow morning. And update any other resources
that reference the file path.

3) The base React SPA layout is the same. David should continue from there.
I've implemented lazy loading to reduce the initial page file load. It's
not server-side rendered yet. Additional JS resources are code split in the
JS bundle and loaded when requested. That's what React Suspense is being
used for. I've implemented a custom theme for Material UI. It basically
overrides the default theme of Material UI. I've also used React Router V6.
David is in a better place to continue working on it.


Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
@bernardbaker I think the change pertaining to (1) is good but the fixes to the unit tests should be included in this PR, or we can refactor the python code locations in a follow up PR that also fixes the tests. I think the latter is the easier (less time cost) option. 

Re: SPA, Sounds good I'll defer to @dzx11's review to make sure we're all aligned on next steps.

**Comment by bernardbaker** [comment]
@un7c0rn Ok. (1) I agree. (3) The work is in this PR. @dzx11 if you have any question about getting started or don't understand anything at all..... please reach out to me. And as @un7c0rn said review the code. You will see that it's the same, with improvements. Might be a good idea to review the project document for the correct page URIs. @un7c0rn can you finalise them?

https://docs.google.com/document/d/1ZfS1JQrqZ4bhy63KcxmfJudwLchiIeXaRBpMaa0tNDo/edit

Page URIs should be pretty and use hyphens, rather than underscores.

**Comment by un7c0rn** [comment]
@bernardbaker Sounds good I created a tracking issue for myself to move the Python code and fix the tests here: https://github.com/un7c0rn/stopthevirus/issues/15

**Comment by bernardbaker** [comment]
Great!

Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
[NOTE] Challenge submission page looks great so far and can be found using this link:

http://localhost:3000/challenge-submission/0044703947287/789632

Thanks @bernardbaker!

**Comment by bernardbaker** [comment]
Probably best to copy the code and structure for other pages.

Guide is in the front end readme.

**Comment by dzx11** [comment]
@bernardbaker I'm a bit confused with how the routing lines up with the pages in the UX design doc. I see that /instructions -> game-info page, and /challenge-submission is the challenge-submission page, but what about the rest of the pages, and which one is /vote in the doc? The doc I'm referencing is this (on page 9): https://docs.google.com/document/d/1ZfS1JQrqZ4bhy63KcxmfJudwLchiIeXaRBpMaa0tNDo/edit
It would probably be a good idea to make the routes line up with what they are in the doc to avoid confusion. 

Also, shouldn't the files have .jsx extension instead of .js if they have JSX components?
We should probably completely delete the virus-fe directory in this PR also, and I agree with renaming this directory to use undescores.
Should probably delete the console logs in App.js and rename TicTok service to TikTok. 
Otherwise looks good on my end. 
edit: Also be sure to remove the yarn.lock file from the PR, I think it should already be in the .gitignore but if not it should be added.

**Comment by un7c0rn** [comment]
@bernardbaker @dzx11 for consistency I've updated the routes in the UX doc diagrams to:

start-game
join-game
game-info
challenge-submission
create-challenge

There's no vote route in the UX spec because voting is currently planned to be done via text response directly in SMS thread. Open to revisiting this if we want to provide a better experience after MVP.

Interested in everyone's perspectives here.

Thanks,
Brandon

**Comment by bernardbaker** [comment]
As I was only working on the challenges submission page. I didn't want to
make additional changes to routes, etc.

But I wanted you to be aware that this needed to be addressed before making
any changes. There used to be a vote route in the wireframes.

JSX describes large HTML like files which React understands. Only
functional components should be used with the React version employed. So we
should use .js files. Along with ES6 style JavaScript style programming.

.js files return JSX, etc. Which is used by React in the virtual DOM.
There's no need for JSX files.

I'll align the routes to the doc in a small PR.

The logs are needed by David and I. Thought they'd help him and my self
when working locally.

I'll build a logger that doesn't log in production. I'll create a PR for
it. And merge it into develop for everyone to use.

I keep on getting that til tok wrong in my spelling. I'll update it.

All this will be worked on tomorrow 🧗.

I'm available via email. But won't be doing any programming. David get in
touch when you're available.

I'd like to discuss the logger with you.

**Comment by dzx11** [comment]
@bernardbaker sounds good, you can email me at (removed)

**Pull request merged**
