### PR TITLE
design automated acceptance test object model.

### PR DESCRIPTION
**Pull request by un7c0rn**

### CODE REVIEW

**Comment by un7c0rn** [comment]
@bernardbaker @dzx11 PTAL. WIP

**Comment by bernardbaker** [comment]
Ok taking a look at it now.

**Comment by bernardbaker** [comment]
Sorry, picking this up now. Had a project related call...

**Review by bernardbaker — APPROVED** [review]
My Python is basic so I think you're obviously the best candidate to approve knowing it works.

**Review by dzx11 — APPROVED** [review]

**Pull request merged**
