### PR TITLE
Feature/matchmaker

### LINKED ISSUE #137: Design the match maker service for merging and starting games

### PR DESCRIPTION
**Pull request by dzx11**
Closes #137 
I'm working off the assumption that this should just be a simple function that takes in players and team size and divides them equally, so some of the code is taken from GameSimulator. @un7c0rn  PTAL

### CODE REVIEW

**Comment by bernardbaker** [comment]
Hi guys,

I'll be working on all page layouts today.

Regards,
Bernard

**Comment by un7c0rn** [comment]
@bernardbaker Awesome! 
@dzx11 Looking at this as well as your design doc now. Thanks!

**Comment by bernardbaker** [comment]
Hi,

Getting started after lunch. All pages will be updated in a few hours.

Regards,

Bernard T. A. Baker

**Comment by dzx11** [comment]
Closing because merging this into https://github.com/un7c0rn/stopthevirus/pull/162

**Pull request closed without merging**
