### PR TITLE
Feature/start game page develop

### LINKED ISSUE #13: UX: [Start a game page] Design / implement basic page layout using material UI components

### PR DESCRIPTION
**Pull request by dzx11**
Closes #13 
A few notes:
-Test by going to /start-game
-Validation is displayed after the submit button is pressed
-Validation for TikTok and Game Name is a check to see if something was entered
-Validation for Phone number is a check to see if the string is length 6 or longer (in practice this is 3 numbers because of the characters for the country code)
-The text fields section gets longer on resolutions <650px height so the layout looks correct for iPhone5SE

### CODE REVIEW

**Review by bernardbaker — COMMENTED** [review]
@dzx11 could you check and make sure that the total viewport height consumed by this page is 100vh.

So each component needs a height of X vh. And when the composite components form the page. The total will be 100vh at all times.

**Review by bernardbaker — CHANGES_REQUESTED** [review]
@dzx11good job 🤸

1) could you update the front end readme.md with the available scripts in the package.json file.

2) add your feature test instructions to the bottom of the readme.md.

3) use react testing library to test the page you have built.

**Comment by un7c0rn** [comment]
+1 Great work! @dzx11

**Comment by bernardbaker** [comment]
@dzx11  LGTM. Tests are passing, I've increased the Jest test timeout. Please run tests again.

**Pull request merged**
