### PR TITLE
Base React SPA with placeholder routes and pages

### PR DESCRIPTION
**Pull request by dzx11**
This will add the basic React app. To test this, it should be sufficient to navigate to the /virus-fe directory, run 'npm install' and then 'yarn start'

### CODE REVIEW

**Comment by bernardbaker** [comment]
Hi *dzx11*,

Welcome to the COVID-19 #STOPTHEVIRUS developer team.

Thanks for your work on this. You didn't know that we are working on
another repository. I've sent you a collaborator invitation.

When you accept the invite, send me an email.

*Some information about the repository*
The *master* branch is what is online here
https://stopthecovid19virus.netlify.com/.
The *develop* branch is what we branch off to create new features.
We create a *pull request* which should only be merged back into *develop*.

*Directions to get started*
Clone the repository. Read the README.md for instructions. Always work off
a branch from the *develop* branch.


Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
@dzx11 Tested and looks good. Thanks!

@dzx11 @bernardbaker 

We initially created the second repo due to Netlify integration requirement and hackathon time constraint. Since the FE is still very early stage I think it makes sense to unify repos now for a number of reasons:

1. Demonstrating progress to external stakeholders
2. Continuous integration tests (even if we only have 1 PR builder test, it's nice to have)
3. Single source of documentation

Please share instructions or any associated keys for Netlify deployments and I can add them to this repo.

**Comment by bernardbaker** [comment]
Ok.

**Comment by dzx11** [comment]
Hi @bernardbaker  @un7c0rn , sorry if I accidentally stepped on anyone's toes. I will probably start working on the start game page next if that's ok.

**Comment by bernardbaker** [comment]
Hi everyone,

I've created a PR https://github.com/un7c0rn/stopthevirus/pull/12. This
actions the points outlined by @un7c0rn.

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
@dzx11 you haven't stepped on anyone's toes.

This is an agile development and some things are changing as new decision
are made, discussions are heard, or opinions unified.

Welcome to the team.

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
Hi,

I've unified the repository.

Immediate access to Netlify as a team member on my account costs $15.00
(USD) a month.

I'm willing to pay for your licenses, which I would bill back to you.

But I think it would be much more cost-effective for you to set up a
Netlify account at https://www.netlify.com, which you can manage and simply
add collaborators using GitHub to contribute to the project(s).

Details are in the PR.

Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
@bernardbaker Awesome thank you. Let's proceed with local deployments and as we approach our launch date I'll setup a prod Netlify account per your instructions. 

@dzx11 start game page sounds perfect. I've updated you as item owner in our UX doc:

https://docs.google.com/document/d/1ZfS1JQrqZ4bhy63KcxmfJudwLchiIeXaRBpMaa0tNDo/edit?usp=sharing

The three of us have edit access to this document.

**Pull request merged**
