### PR TITLE
Fix/patch

### PR DESCRIPTION
**Pull request by bernardbaker**

### CODE REVIEW

**Comment by un7c0rn** [comment]
@bernardbaker looks like there's a merge conflict.

**Comment by bernardbaker** [comment]
Thanks for the update.

I had some trouble when I last worked on it. It wouldn't update if I
remember correctly. So I couldn't see the conflict.

I'll tackle that tomorrow.

Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
SGTM

**Comment by bernardbaker** [comment]
Stale branch.

**Pull request closed without merging**
